-- 面板宽度持久化：真实窗口、关闭清理，以及独立 Neovim 重启后读回
local H = dofile('tests/helpers.lua')
local T, child, restart = H.new_set()
local expect = require('mini.test').expect

T['调整宽度、关闭与退出均保存宽度且新进程可恢复'] = function()
  local exit_width = child.lua_func(function()
    local State = require('vv-utils.state')
    local Replace = require('vv-replace')
    local Buffer = require('vv-replace.buffer')
    local path = vim.fs.joinpath(vim.env.VV_TEST_TMP, 'state.json')
    local state = State.register('vv-replace', 'panel', { path = path })
    assert(state:set('width', 'invalid'))
    local function resize(width)
      vim.cmd('vertical resize ' .. width)
      -- headless 没有 UI redraw，显式派发生产 autocmd
      vim.api.nvim_exec_autocmds('WinResized', {})
    end
    Replace.setup({ width = 29, width_save_debounce_ms = 20, debounce_ms = 60000,
      history_persist = false, state = state })
    Replace.open()
    local ctx = assert(Buffer.current)
    assert(vim.api.nvim_win_get_width(ctx.win) == 29, '非法宽度必须回落到配置宽度')
    resize(41)
    local resized = vim.api.nvim_win_get_width(ctx.win)
    assert(vim.wait(30000, function() return state:get('width') == resized end), 'WinResized 必须防抖保存宽度')
    Replace.close()
    assert(state:get('width') == resized, 'close 必须同步保存宽度')
    Replace.open()
    ctx = assert(Buffer.current)
    assert(vim.api.nvim_win_get_width(ctx.win) == resized, '重开必须恢复宽度')
    resize(43)
    local external = vim.api.nvim_win_get_width(ctx.win)
    vim.cmd('quit')
    assert(Buffer.current == nil, '外部 WinClosed 必须释放 context')
    assert(state:get('width') == external, '外部 WinClosed 必须保存宽度')
    Replace.open()
    ctx = assert(Buffer.current)
    resize(45)
    local exiting = vim.api.nvim_win_get_width(ctx.win)
    vim.api.nvim_exec_autocmds('VimLeavePre', {})
    vim.api.nvim_exec_autocmds('VimLeavePre', {})
    assert(state:get('width') == exiting, 'VimLeavePre 必须同步保存宽度')
    assert(State.register('vv-replace', 'panel', { path = path }):get('width') == exiting, '新句柄必须读到持久化的宽度')
    Replace.close()
    return exiting
  end)
  restart()
  local restored = child.lua_func(function()
    local State = require('vv-utils.state')
    local Replace = require('vv-replace')
    local Buffer = require('vv-replace.buffer')
    local state = State.register('vv-replace', 'panel', { path = vim.fs.joinpath(vim.env.VV_TEST_TMP, 'state.json') })
    Replace.setup({ width = 29, debounce_ms = 60000, history_persist = false, state = state })
    Replace.open()
    local width = vim.api.nvim_win_get_width(assert(Buffer.current).win)
    Replace.close()
    return width
  end)
  expect.equality(restored, exit_width)
end

return T
